* Join EmacsTalk
本仓库主要记录嘉宾在参与 EmacsTalk 录制前的一些准备事宜。

理论上每一期的节目会在 podcasts 文件夹内新建一个名为 ={id}-{guest-name}= 的 org/md 文件，比如 =001-xigua.org= ），id 是递增的，表示第几期节目，文件内容为下面的录制大纲。

** 录制流程
1. fork 本仓库，创建自己的文件，填写录制大纲的内容。嘉宾不需要花费太多精力，可以罗列一下关键字，主要的目的还是让嘉宾熟悉下自己要讲的内容。嘉宾也可自由发挥，后续 review 时主播会与嘉宾进行细节沟通。
2. 提 PR，主播会进行 review，同时也会进行微信语言沟通
3. 约时间，推荐在周末。
4. 节目录制
5. 去噪、合并音轨
6. 发布，同步到各个社交平台

- 1-2 为嘉宾的工作
- 3-4 为主播与嘉宾公共进行
- 5-6 为主播的工作

** 录制大纲
1. 嘉宾个人简介，5-10 分钟
   1. 姓名，网络 ID，社交信息
   2. 工作经历
   3. 目前 Emacs 的配置，包括：GUI/终端、版本等
2. Emacs 初印象，5-10 分钟
3. Emacs 学习经历，10-20 分钟
   1. Emacs 的推荐学习方式
4. 日常工作流，10 分钟
5. Share 环节，推荐以下内容，5分钟
   1. Emacs package，最好是两三句话能够描述清楚的，可以是自己写的或自己重度使用的
   2. 其他相分享的东西，不需要和 Emacs 有关

** 录制方式
理论上所有的录制都采用远程方式，这也是大多数 Podcasts 做法。根据主播的了解，一般的采用的方式是：
- 主播与嘉宾分别录制自己的声音，最后在剪接时把多个声轨合并成这一个

这也可以最大程度避免网络带来的不确定性，我这里提供一个操作方式供参考：
#+begin_example
带着耳机通过手机收听对方的声音，然后在电脑端代用录音软件（macOS 直接使用 voice memos 即可）进行录制。
#+end_example
之所以分开来，是由于我发现 iPhone 自带的录音软件没有暂停录制的功能（电脑端有），只能一口气录完，这不是很现实。嘉宾可根据自身情况选择录制方式。

** 注意事项
- 录制过程尽量避免打断，比如可以手机开飞行模式
- 如果录制中出现打断，可以暂停一下，后续剪辑掉即可，最好不要在正文中掺杂一些不需要的声音

** 写在最后
- 感谢每一位嘉宾的参与，希望您在 EmacsTalk 能有自己的收获
- 主播目前工作地在杭州，如果嘉宾也在同一城市，可以选择当面录制。
