#+TITLE: Jin Guo (stardiviner)

* 嘉宾个人简介
- 名字：金国
- 网络昵称： [[https://stardiviner.github.io/][stardiviner]]
- 社交信息：基本很少使用社交媒体，除了微信偶尔有两三个朋友发下信息外。基本不和人联系。
- 工作经历：干过除了程序员之外的大多数工作
- 目前 Emacs 的配置： macOS 下homebrew版本的Emacs

* Emacs 初印象

1. Emacs给我的印象就是强大，并且有很多厉害的黑客使用。跟着大宗师的路走没错。
2. 一开始是带着一点宗教意义上的盲目崇拜，仿佛学会了Emacs就能用它变得无所不能。男
   孩子嘛，总是希望手中有一把长剑，学会剑术后，梦想从此仗剑走天涯。而Emacs就是我
   手中的长剑。

* Emacs 学习经历

1. 由于经济和家庭原因，我接触电脑比绝大多数同龄人都晚，大学才接触的电脑，大二买
   了一台华硕1000H的很小的笔记本电脑后，由于系统坏了，就找华硕的售后去修，看师傅
   那插上外接硬盘安装系统，觉得很厉害。问师傅不肯说。就回来后自己上网学。然后就
   此踏上了学习电脑技术的路。在几十次重装系统后，终于掌握了熟练的安装系统技巧，
   意外的接触了Linux，以及Conky，还有Vim。
2. 在使用和学习了2年多Vim之后，又看上了Emacs家强大的的Org Mode。于是又转投Emacs娘的怀抱。
3. 在经过一段时间难受的适应磨合期后，就顺利过渡到了Emacs，前期也是和很多人一样，
   抄别人的配置。但是在实际修改过程中发现，其实完全没必要，抄别人配置不仅不符合
   自己的需求还费劲改，直接自己从头开始写，反而更好维护，而且还能提高自己的能力。
4. 有很长一段时间都关注MELPA新出的插件。
5. 安装使用过很多的插件，虽然没有特别深入的，但是大多数插件都接触了解过。
6. 由于提交插件bug或者问别人问题，总是力不从心，而且插件作者也不见得会即刻解决你
   的需求。所以就自己开始学习Emacs Lisp语言。建议大家都学一点Emacs Lisp，这样对
   你自己好，对插件开发者好，也是对整个社区都是一种巨大的提升。
7. 由于中间断断续续进去看过Org Mode的部分源代码，也follow了Org Mode的邮件列表，
   看过别人提交patch补丁。于是自己也提交了下，从此开始了给Org Mode提交补丁和新功
   能的路。
8. 之后就渐渐能自己开始写一些小的插件，然后自己维护自己的插件，也会接过一些别的
   作者已经不再维护的插件。
9. 我写的那些插件
   - kiwix.el
   - org-link-beautify
   - org-tag-beautify
   - rainbow-fart
   - org-kindle
   - arduino-mode
   - some other org-mode babel languages supports
10. 不过现在我的需求变少了，而且Emacs配置也变稳定了，所以很少再修改Emacs设置了。

* 日常工作流

- 主要是使用Org Mode记录信息。比如任务，日记，笔记，电子书，音频视频资料，编程代
  码等等。把Org Mode数据库当作一个第二大脑。
- 使用Emacs写一点Clojure代码。
- 使用Emacs看RSS新闻
- 使用Emacs看书，记笔记

* 淘宝店自由职业者经历

** 沟通开始就很有问题

- 新手通常喜欢先问“在不”，然后等你回复，你不回复，他就不说话。
- 即使我设置了自动回复的模版说“直接说详细问题”，有一部分人也不看。
- 问的问题也是很小白，比如“我的某某软件打不开了”，其实他是软件无法编译C，或者无
  法运行，但是软件vscode打开是很正常的。我告诉他们以后要先尽量弄清楚问题，这样提
  问才有效，但是他们的回复是“我就是因为是小白，不懂才来问题，不然我就不问你了”。
  你看，这个就是自我意识的问题，觉得小白不懂是自然而然的，他们不寻求自我的解救之
  法，等着别人来救。等着一个高手来全能的了解所有问题，给他解决问题。自己只要等你
  高手说就行。这个其实就是《天道》里面的中国农民意识，等着有一个英雄，上位者来赐
  予他们。我这个是上升到某一个高度了，可能大家觉得有点过头，其实不是的，这就是民
  族文化意识问题。你做这件事是这样，做其他事也是这样的。比如社会问题，等着政府做
  点什么，等着公司做点什么。大家都等着别人做点什么。

** 如何提问

- 建议阅读  [[http://catb.org/~esr/faqs/smart-questions.html][How To Ask Questions The Smart Way]]

** 一定要多思考，反思自己的行为

因为我以前有时会遇到脾气不好的开发者，他们会嫌弃我提问不完善，不自己学习。一开始
觉得很不友好，但是自己反思后，觉得人家是对的。虽然有情绪，但是我直到是对的就行，
于是我就自己去学，去晚上提问时的资料信息。因为毕竟回答你不是人家的义务，其实我是
不赞同宣传人员宣传社区多么多么友好的。这只会给社区带来负担。给别人一个错误的固有
印象。

就像我开淘宝店，有的客户一开始就态度不好，仿佛他是客户，我就天然欠他的，不服务好
就是我万恶。先不说他还没付钱让我服务，即使付钱了也没道理做我服务范围之外的事。我
多做纯粹是出于好心情和客户对我的态度友好。这个其实是一种服务消费主义的错觉，你在
其他的地方得到很好的服务，以为世界上所有地方都应该有很好的服务。这太想当然了，这
就像是在固有观念上强迫所有女生都要表现的温柔可人一样，世界上也可以有女子勇敢大胆。
说到底就是当现实发生的事情和你脑子里的观念发生冲突的时候，有的人是否定现实，朝对
方骂脏话，给差评；很少的人是去反思自己，这样的人就是“实事求是”。这大概就是电视剧
《天道》里面丁元英讲的“实事求是”吧。不是他神，而是这个世上很多人都不实事求是。

* Share

- 学了Emacs一定要学Org Mode，因为真的很强，你几乎可以用它来做很多事。这个是对于
  追求统一的用户来说的福音。如果你觉得管理任务，用下GTD类软件就行的那种，还是不
  建议的。

* 其他

- Clojure 是一个设计和使用非常好的语言
- Proof General https://proofgeneral.github.io/
- stardiviner 的 [[https://item.taobao.com/item.htm?spm=a1z10.1-c-s.w4004-21943370648.2.30af41dbnBlphe&id=603644408321][蓝鲨网络工作室 （淘宝店）]]

